---
abstract: 'A client for the Neo4j graph database'
author:
  - 'Nuba Princigalli <nuba@stastu.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Neo4j
no_index:
  directory:
    - t
    - inc
requires:
  Class::Accessor: 0
  JSON: 0
  Moose: 0
  REST::Client: 0
  Test::More: 0
  Try::Tiny: 0
version: 0.01_01
